source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'GrowingTextView_Example' do
  pod 'ASGrowingTextView', :path => '../'
end

target 'GrowingTextView_Tests' do
  pod 'ASGrowingTextView', :path => '../'
  
end
